name: "Tests"
on: pull_request

env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: card_hell

jobs:
  test_linux:
    name: Test Linux
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Windows Build
        run: |
          mkdir -v -p ../build/windows
          godot -v --build-solutions